export const ROUTES = {
  INDEX: '/',
  LOGIN: '/login',
  SIGINUP: '/sign-up',
  FORGOT_PASSWORD: '/forgot-password',
  RESET_PASSWORD: '/reset-password',
  VERIFY_ACCOUNT: '/verify-account',
  SIGINUP_SUBSCRIPTION: '/sign-up-subscription',
  SUBSCRIPTION: '/subscription',
  INBOX: '/inbox',
  HISTORY: '/history',
  BOOK_APPOINTMENT: '/book-appointment',
  CHOOSE_APPOINTMENT: '/book-appointment/choose-appointment',
  REVIEW_APPOINTMENT: '/book-appointment/review-appointment',
  CONFIRM_BOOKING: '/book-appointment/confirm-booking',
  DOCTORS: '/doctors',
  VIEW_BOOKING: '/history/view-booking',
  RESCHEDULE_APPOINTMENT: '/reschedule-appointment',
  PROFILE: '/profile',
  CHANGE_PASSWORD: '/profile/change-password'
};
