const KEYS = {
  INDEX: 'INDEX',
  LOGIN: 'LOGIN',
  SIGINUP: 'SIGINUP',
  FORGOT_PASSWORD: 'FORGOT_PASSWORD',
  RESET_PASSWORD: 'RESET_PASSWORD',
  CODE_VERIFICATION: 'CODE_VERIFICATION',
  SIGINUP_SUBSCRIPTION: 'SIGINUP_SUBSCRIPTION',
  SUBSCRIPTION: 'SUBSCRIPTION',
  INBOX: 'INBOX',
  HISTORY: 'HISTORY',
  BOOK_APPOINTMENT: 'BOOK_APPOINTMENT',
  CHOOSE_APPOINTMENT: 'CHOOSE_APPOINTMENT',
  REVIEW_APPOINTMENT: 'REVIEW_APPOINTMENT',
  CONFIRM_BOOKING: 'CONFIRM_BOOKING',
  DOCTORS: 'DOCTORS',
  VIEW_BOOKING: 'VIEW_BOOKING',
  RESCHEDULE_APPOINTMENT: 'RESCHEDULE_APPOINTMENT',
  PROFILE: 'PROFILE',
  CHANGE_PASSWORD: 'CHANGE_PASSWORD'
};

export default KEYS;
